"""create daily qr table

Revision ID: 2b00151c47a4
Revises: 78a50b3cb708
Create Date: 2026-02-13 09:36:07.567673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b00151c47a4'
down_revision = '78a50b3cb708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_qr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('token', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_qr', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_qr_day'), ['day'], unique=True)
        batch_op.create_index(batch_op.f('ix_daily_qr_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_qr', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_qr_token'))
        batch_op.drop_index(batch_op.f('ix_daily_qr_day'))

    op.drop_table('daily_qr')
    # ### end Alembic commands ###
