"""create attendance table

Revision ID: 78a50b3cb708
Revises: 9be3325cbcbe
Create Date: 2026-02-13 09:07:49.477090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a50b3cb708'
down_revision = '9be3325cbcbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('am_in', sa.Time(), nullable=True),
    sa.Column('lunch_out', sa.Time(), nullable=True),
    sa.Column('lunch_in', sa.Time(), nullable=True),
    sa.Column('pm_out', sa.Time(), nullable=True),
    sa.Column('total_minutes', sa.Integer(), nullable=False),
    sa.Column('overtime_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'day', name='uq_att_employee_day')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_employee_id'), ['employee_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_employee_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_day'))

    op.drop_table('attendance')
    # ### end Alembic commands ###
