"""create visitor table

Revision ID: 981804725e38
Revises: 2b00151c47a4
Create Date: 2026-02-13 10:10:56.213497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981804725e38'
down_revision = '2b00151c47a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('contact', sa.String(length=80), nullable=True),
    sa.Column('purpose', sa.String(length=200), nullable=True),
    sa.Column('time_in', sa.DateTime(), nullable=False),
    sa.Column('time_out', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitor')
    # ### end Alembic commands ###
