"""update employee fields

Revision ID: 9be3325cbcbe
Revises: da929581685d
Create Date: 2026-02-13 08:47:25.512288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be3325cbcbe'
down_revision = 'da929581685d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surname', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('middle_name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('birthday', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('position', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.drop_column('department')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('department', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('is_active')
        batch_op.drop_column('status')
        batch_op.drop_column('position')
        batch_op.drop_column('birthday')
        batch_op.drop_column('middle_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('surname')

    # ### end Alembic commands ###
